#----------------------------------------------------------------------
# This file was generated by make.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

catalog = {}
index = []

undo16x16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAAK/INwWK6QAAABl0"
    "RVh0U29mdHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAJVSURBVHjaYmTAAqyMjeXtWFk3"
    "fPz48dn069e9GfAAgABiQhdwVVOzD1NSulC7bZuBBCenOAMBABBAKMhLXr5+W3Pz//9v3/7/"
    "/+bN/0YdnaceSkrxQBfx49IDEEAwJ/PnGhntf7Rq1f//N278/3/t2v//V678/3/x4v9Hy5b9"
    "nxUZ+R5kODa9AAHECLRB31pW9kBRVZUAFy8vA8OfPwwMf/9i0I+vXGGoWrjwwD1e3oBjZ89+"
    "hBkAEEBMLL9/OwTHxgpwgXgvXzIwvH4NoV+8YGB49gyCHz9mkOXmZuj383NQevlyGbILAAKI"
    "+danTyfvnzv3mY2V1V1bTo6B4eZNBoa3bxkY3r2DGPbqFcTAJ08YuIC09p8/qjc4OT/fe//+"
    "OMgAgABiBhG3P306/vr58+0PHz0KNfPy4mAFafjwgeEwUO69uDgDn64uA+vv3wwMjx4xiLCy"
    "Mnz59Mnqmbj4rBevX38HCCBmmFMefPz49AM7+5ybJ09a6rq4yPNzcTHMW7fuZtfp04k7V6/+"
    "/ltCwsggJISB4epVBomfP9m3f/jwGKjnFEAAYY0VD3n5pm2Vlf8b/f3PwMTM9PWNay0tL32d"
    "M+f/f1vb/1lSUntA4gABhBPZKSm52UhIJKGn0Al+fu//t7T8n6Ko+B8oxAkQQAykAlDCujZ5"
    "8v+d2tr/dTU0bAACiJlUA+68f39R6v//BEt1dYF1z56tBwggJgYywPGrVye8FRNjYP32TQwg"
    "gMgy4J2Y2IHTFy4wCH//rgUQQMzkGPD4+fOXApycZo9//94GEGAA2rH5UKps700AAAAASUVO"
    "RK5CYII=")
index.append('undo16x16')
catalog['undo16x16'] = undo16x16

#----------------------------------------------------------------------
computer_desktop_icon16x16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAAK/INwWK6QAAABl0"
    "RVh0U29mdHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAOWSURBVHjaYvz//z8DCKSmZmy0"
    "tDRT4eJkY2dlZmVlZmJhY2FiYWFiZGVjZAJyOLlYb919/K6gIMXy168fz4BafoL0AQQQCwMU"
    "ODu7OaioaPCV125j+McuwvCHiZHhNxMzw5//jAx/fjMwsPx+zFAQJSPKzMxkA1S+C4hfA/E/"
    "gACCG3D58uVzivLqDvtO/2NgkOJnYBDlYWDg52ZgYGVmYPj/l4Hh1SuG91/YmISFRXSfPHl0"
    "AqjlHcgAgABighlw796ji+Ji3Ayy6kDNYkDNsgIMDHJiDAwKUgwM0sIMDNycDK++MDLISEnJ"
    "AJVzwlwPEEBwA969e3/+37+/DGpyQM1vPwN9CLT1NzB8vv5iYHgJtOz9N4bHH4HmyStKA5Vz"
    "wAwACCC4Ad++/bj86tWbnwZ6okDNwPB5/4mB8fVLBub3LxkYWYAGiQsy3P3MxKCoqCyB7AKA"
    "AIKHwadP724/ePD8uaG2ogID3zeg//kYmPhZGbi4WBj+AUPxJ9CQv8zfGFRVNcQYGRmFgLHH"
    "CtIHEEBwA1hYOL6+fP3hk4MBP4Oq2m8GaVUGBm2gY0VYPjNI8bEzSPDxM3AB4cXzj/4zM7Pw"
    "//nzG2QAI0AAwQ0ICor3FxEV0/nz/RvDkiwlhm+fvzKcP3fi3YlTJ+9vvX/v5YePH1+8fvP6"
    "1afPHx7////vAVDLH5A+gACCG6CkJBWsr6/M9PLlG4avXz8xvH37gWHrrh3v9u7bOQUo/RKI"
    "gUHI8AOIv4N8DMX/AQIIbsCZMyfvi4ry/BAREeRgZ2dhYGRkYwgLT1QRFpMt0jW0YuLi5OO+"
    "df3iwUvnT047fmLXA6hhDAABhBSI34Tevv3G/vr1dwZJGTEGeRVNBmVdCwaXwHDdb8CY/AK0"
    "V9fMScHM9Ejg9x8fGy9cODkHqO0LQADBo/H8+RO7T588ep6N6f8vhr+MwDT2n4GN6Q/D9w9v"
    "GL6/fsjA9PEpgwowAiMjfPk8Pf3ygVrkQNEJEEBwF5w9e3DH8zdPfv8SVpxjz/pP4uf3twxa"
    "OjoM/IIcDJ9Y/jA8evT454pdR16uXbvqyoULp/cAtXCDfAAQQIyw3Ghlbsr9VCziPL+ej6rc"
    "30cM+vxfGe5c3Hbz8qXjl549e/r48+ePj//9+/cU5GxoPngOxK8AAgjuAnZO7j8s9zdst1H8"
    "JSgmKcN55tSB+9s2zp8LtOAOUPoNVCMwhTF8hcYECP8BCDAASVROeCfL8fUAAAAASUVORK5C"
    "YII=")
index.append('computer_desktop_icon16x16')
catalog['computer_desktop_icon16x16'] = computer_desktop_icon16x16

#----------------------------------------------------------------------
led_grey_icon16x16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAAmJLR0QA/4ePzL8AAAAJcEhZ"
    "cwAACxMAAAsTAQCanBgAAAAHdElNRQfUCw0UEzCc2GfHAAABbklEQVR42n2Rv0tbYRSGn3Pu"
    "p73GJCCFdhA0BGkHt4g61xKLlIASB4ciCILon9DJ3b2tFCqC4lKTilDs0G6lg0YEFSl0E4u/"
    "WjS3BjW539fhGsHF8y7vOe/zTkdOuH8MzNBEMxUuRvzRloyfuDg/2Did06LHJUuYiKu2P3z7"
    "bCBFDCAW5HZzX4unU3pIBNTaWr/1peMIDsHRTDcdQwtPNp9zpOA8/31v+gEhFofFYgmJk+80"
    "7xAF8qn+kPAmCG8ReDn4+IWB5PgjAmL4OATB4bBUCEiTGTPQkmlCOCNBIx4AIVf8Q/HpyBiI"
    "xQ0ehmtCFMFhCWlAsCSSClI2NGAwKAIIiiG6BWWFYN3hoSgeHgbvdrP8LCn8nj1GEPSOBOEX"
    "G/MKldUfKzUEQW7aka+x8OnvmgJuf+LjTh2pt6u82f0yiVMAPSpkp5e3qQIOxxVbvC58yNr6"
    "L6B6WBz+PtDz6mlXMnlW3iutL/75HCX/AWZafCjm+7rjAAAAAElFTkSuQmCC")
index.append('led_grey_icon16x16')
catalog['led_grey_icon16x16'] = led_grey_icon16x16

